config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :places, shallow: true do
    resources :ratings
  end

  root to: 'visitors#index'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/place.rb
class Place < ActiveRecord::Base
  has_many :ratings
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :place
end

app/models/user.rb
class User < ApplicationRecord

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      if auth['info']
         user.name = auth['info']['name'] || ""
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :user_signed_in?
  helper_method :correct_user?

  private
    def current_user
      begin
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
      rescue Exception => e
        nil
      end
    end

    def user_signed_in?
      return true if current_user
    end

    def correct_user?
      @user = User.find(params[:id])
      unless current_user == @user
        redirect_to root_url, :alert => "Access denied."
      end
    end

    def authenticate_user!
      if !current_user
        redirect_to root_url, :alert => 'You need to sign in for access to this page.'
      end
    end

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  def new
    @place = Place.new
  end
  
  def create
    @place = Place.create(place_params)
    if @place.errors.empty?
      redirect_to @place
    else
      render 'new'
    end
  end
  
  def show
    @place = Place.find(params[:id])
  end

  private
  def place_params
    params.require(:place).permit(:name, :address, :description)
  end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to '/auth/google_oauth2'
  end

  def create
    auth = request.env["omniauth.auth"]
    user = User.where(:provider => auth['provider'],
                      :uid => auth['uid'].to_s).first || User.create_with_omniauth(auth)
    reset_session
    session[:user_id] = user.id
    redirect_to root_url, :notice => 'Signed in!'
  end

  def destroy
    reset_session
    redirect_to root_url, :notice => 'Signed out!'
  end

  def failure
    redirect_to root_url, :alert => "Authentication error: #{params[:message].humanize}"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user?, :except => [:index]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li class='nav-item'><%= link_to 'Sign out', signout_path, class: 'nav-link' %></li>
<% else %>
  <li class='nav-item'><%= link_to 'Sign in', signin_path, class: 'nav-link' %></li>
<% end %>
<% if user_signed_in? %>
  <li class='nav-item'><%= link_to 'Users', users_path, class: 'nav-link' %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 4.0 %>
<div class="container">
  <nav class="navbar navbar-dark bg-inverse">
    <ul class="nav navbar-nav clearfix">
      <li class="nav-item">
        <button class="navbar-toggler hidden-sm-up nav-link" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2" aria-controls="exCollapsingNavbar2" aria-expanded="false" aria-label="Toggle navigation">
          &#9776;
        </button>
      </li>
    </ul>
    <div class="collapse navbar-toggleable-xs" id="exCollapsingNavbar2">
      <%= link_to "Rails bootstrap", root_path, class: 'navbar-brand' %>
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li class='nav-item'><%= link_to 'About', page_path('about'), class: 'nav-link' %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
	<title>Lunch on Rails - keep track of your lunch breaks<</title>
    <%= csrf_meta_tags %>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'true' %>
	<link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'true' %>
  </head>
  <body>
    <%= yield %>
  </body>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>Sample page</h3>
<p>
Link to <%= link_to('this', 'http://github.com/mkrl') %>.
</p>

app/views/places/new.html.erb
<h1> Add a place</h1>
<%= form_for @place, url: places_path do |f| %>
  <p><%= f.text_field :name %></p>
  <p><%= f.text_field :address %></p>
  <p><%= f.text_field :description %></p>
  <p><%= f.submit "Add a place" %></p>
<% end %>

app/views/places/show.html.erb
<h1>Welcome to <%= @place.name %>!</h1>
<p>Address: <%= @place.address %> </p>
<p>Lunch hours: <%= @semester.description %> </p>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>

app/views/visitors/index.html.erb
  <body id="page-top">

    <!-- Navigation -->
    <nav class="navbar navbar-toggleable-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="#page-top">Lunch <i class="fa fa-cutlery" aria-hidden="true"></i> on Rails</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
			<li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#about">Statistics</a>
            </li>
			<% end %>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#places">Places to go</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <header class="masthead text-center text-white d-flex">
	
	<div id="videolunch" class="bg_lunchvideo">
		<video id="video" width="100%" height="auto" autoplay="autoplay" loop="loop" preload="auto">
			<source src="/img/lunch.mp4"></source>
		</video>
	</div>
	
      <div class="container my-auto">
        <div class="row">
          <div class="col-lg-10 mx-auto">
				<div class="lunch-circle">
					<div class="lunch-face">
						<div id="hour" class="lunch-hour"></div>
						<div id="minute" class="lunch-minute"></div>
						<div id="second" class="lunch-second"></div>
					</div>
				</div>		  
            <h1 class="text-uppercase">
              <strong id="clock">...</strong>
            </h1>
            <hr>
          </div>
          <div class="col-lg-8 mx-auto">
            <p class="text-faded mb-5" id="countlunchdown">Take your time</p>
			<% if user_signed_in? %>
            <a class="btn btn-primary btn-xl open-popup-link" href="#launchlunch">I'm going now</a>
			<% end %>
          </div>
			<div id="launchlunch" class="white-popup mfp-hide">
			  <h1 class="text-center">Pick a place to go</h1>
			</div>
        </div>
      </div>
    </header>


	<% if user_signed_in? %>
    <section class="bg-dark" id="about">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 mx-auto text-center">
            <h2 class="section-heading text-white">Your lunch overview</h2>
            <hr class="light my-4">
          </div>
        </div>
		      <div class="container">
        <div class="row" style="margin-top: 3rem;">
          <div class="col-lg-3 col-md-6 text-center">
            <div class="service-box mt-5 mx-auto">
              <strong><h1 class="text-primary stat_digit">5</h1></strong>
              <h3 class="mb-3 text-faded">Total lunches this year</h3>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 text-center">
            <div class="service-box mt-5 mx-auto">
              <strong><h1 class="text-primary stat_digit">3</h1></strong>
              <h3 class="mb-3 text-faded">Times too late to eat</h3>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 text-center">
            <div class="service-box mt-5 mx-auto">
              <strong><h1 class="text-primary stat_digit">2</h1></strong>
              <h3 class="mb-3 text-faded">Different places visited</h3>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 text-center">
            <div class="service-box mt-5 mx-auto">
              <strong><h1 class="text-primary stat_digit">40</h1></strong>
              <h3 class="mb-3 text-faded">Minutes average lunch length</h3>
            </div>
          </div>
        </div>
      </div>
      </div>	  
    </section>
	<% else %>
      <section class="bg-dark"></section>
    <% end %>
	
    <section class="p-0 bg-primary" id="places">
      <div class="container-fluid p-0">
        <div class="row no-gutters popup-gallery">
          <div class="col-lg-4 col-sm-6">
            <a class="portfolio-box" href="img/portfolio/fullsize/1.jpg">
              <img class="img-fluid" src="img/portfolio/thumbnails/1.jpg" alt="">
              <div class="portfolio-box-caption">
                <div class="portfolio-box-caption-content">
                  <div class="project-category text-faded">
                    Category
                  </div>
                  <div class="project-name">
                    Project Name
                  </div>
                </div>
              </div>
            </a>
          </div>
          <div class="col-lg-4 col-sm-6">
            <a class="portfolio-box" href="img/portfolio/fullsize/2.jpg">
              <img class="img-fluid" src="img/portfolio/thumbnails/2.jpg" alt="">
              <div class="portfolio-box-caption">
                <div class="portfolio-box-caption-content">
                  <div class="project-category text-faded">
                    Category
                  </div>
                  <div class="project-name">
                    Project Name
                  </div>
                </div>
              </div>
            </a>
          </div>
          <div class="col-lg-4 col-sm-6">
            <a class="portfolio-box" href="img/portfolio/fullsize/3.jpg">
              <img class="img-fluid" src="img/portfolio/thumbnails/3.jpg" alt="">
              <div class="portfolio-box-caption">
                <div class="portfolio-box-caption-content">
                  <div class="project-category text-faded">
                    Category
                  </div>
                  <div class="project-name">
                    Project Name
                  </div>
                </div>
              </div>
            </a>
          </div>
          <div class="col-lg-4 col-sm-6">
            <a class="portfolio-box" href="img/portfolio/fullsize/4.jpg">
              <img class="img-fluid" src="img/portfolio/thumbnails/4.jpg" alt="">
              <div class="portfolio-box-caption">
                <div class="portfolio-box-caption-content">
                  <div class="project-category text-faded">
                    Category
                  </div>
                  <div class="project-name">
                    Project Name
                  </div>
                </div>
              </div>
            </a>
          </div>
          <div class="col-lg-4 col-sm-6">
            <a class="portfolio-box" href="img/portfolio/fullsize/5.jpg">
              <img class="img-fluid" src="img/portfolio/thumbnails/5.jpg" alt="">
              <div class="portfolio-box-caption">
                <div class="portfolio-box-caption-content">
                  <div class="project-category text-faded">
                    Category
                  </div>
                  <div class="project-name">
                    Project Name
                  </div>
                </div>
              </div>
            </a>
          </div>
          <div class="col-lg-4 col-sm-6">
            <a class="portfolio-box" href="img/portfolio/fullsize/6.jpg">
              <img class="img-fluid" src="img/portfolio/thumbnails/6.jpg" alt="">
              <div class="portfolio-box-caption">
                <div class="portfolio-box-caption-content">
                  <div class="project-category text-faded">
                    Category
                  </div>
                  <div class="project-name">
                    Project Name
                  </div>
                </div>
              </div>
            </a>
          </div>
       </div>
      </div>
    </section>	

	<% if user_signed_in? %>
      <div class="bg-dark"><ul class="nav nav-justified" id="userbar">
          <li><a href="#" title="Settings"><i class="fa fa-cog fa-2x col-sm-12"></i></a></li>
          <li><a href="#" title="Add a place"><i class="fa fa-plus fa-2x col-sm-12"></i></a></li>
          <li><a href="#" title="Profile"><i class="fa fa-user fa-2x col-sm-12"></i></a></li>
          <li><a href="/signout" title="Logout"><i class="fa fa-sign-out fa-2x col-sm-12"></i></a></li>
        </ul>
	</div>
    <% else %>
      <div class="bg-dark"><ul class="nav nav-justified" id="userbar">
          <li style="width: 100%"><a href="/signin" title="Login" ><i class="fa fa-sign-in fa-2x col-sm-12"></i></a></li>
        </ul>
	</div>       
    <% end %>